# Copyright (c) Jonathan de Bruin
# Distributed under the terms of the Modified BSD License.
FROM jupyter/tensorflow-notebook

LABEL maintainer="Jonathan de Bruin <j.debruin1@uu.nl>"

VOLUME ["/data", "/python", "/notebooks", "/examples"]

# Install libact-lite
RUN pip install git+https://github.com/J535D165/libact-lite.git